spring.application.name=api-gateway
server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.server.webflux.routes[1].id=election-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://ELECTION-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/elections/**

spring.cloud.gateway.server.webflux.routes[2].id=voting-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://VOTING-SERVICE
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/votes/**

spring.cloud.gateway.server.webflux.routes[3].id=result-service
spring.cloud.gateway.server.webflux.routes[3].uri=lb://RESULT-SERVICE
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/results/**